

GET http://localhost:3001/notes


###
POST http://localhost:3001/notes

{
    "title":"dancing in the rain",
    "content":"i love dancing in the rain coz you can multitask like cry and work while no one notices"
}
